<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#1e293b;">
@php
    $period = trim(($filters['fecha_desde'] ?? 'Inicio') . ' a ' . ($filters['fecha_hasta'] ?? 'hoy'));
    $recent = $records->take(10);
    $centers = $analytics['centros'] ?? [];
    $frequencies = $analytics['frecuencias'] ?? [];
    $verifications = $analytics['verificaciones'] ?? [];
@endphp
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:28px 12px;"><tr><td align="center">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:720px;background:#fff;border-radius:9px;overflow:hidden;box-shadow:0 5px 22px rgba(15,23,42,.12);">
        <tr><td style="padding:23px 30px;background:#21064f;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="vertical-align:middle;"><img src="{{ asset('brand/wp/Logo_Saep_email.png') }}" alt="SAEP" width="112" style="display:block;height:auto;max-width:112px;"></td><td align="right" style="vertical-align:middle;"><span style="display:inline-block;background:#00c781;color:#fff;border-radius:4px;padding:7px 9px;font-size:10px;font-weight:800;letter-spacing:.05em;">REPORTE PDR</span></td></tr></table>
        </td></tr>
        <tr><td style="padding:27px 30px 10px;"><h1 style="margin:0 0 7px;color:#21064f;font-size:22px;line-height:1.25;">Inspecciones Preventivas</h1><p style="margin:0;color:#64748b;font-size:13px;line-height:1.55;">Hola {{ $recipientName }}, este reporte reúne las inspecciones registradas en Kizeo para el período <strong style="color:#334155;">{{ $period }}</strong>.</p></td></tr>
        <tr><td style="padding:15px 30px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>
            @foreach([['Inspecciones', $analytics['total'] ?? 0, '#21064f'], ['Condiciones', $analytics['condiciones'] ?? 0, '#ff6b35'], ['Medidas', $analytics['medidas'] ?? 0, '#dc2626'], ['Acción inmediata', $analytics['inmediatas'] ?? 0, '#15803d']] as [$label, $value, $color])
                <td style="width:25%;padding:0 4px;text-align:center;vertical-align:top;"><div style="min-height:77px;padding:11px 5px;border:1px solid #e2e8f0;border-top:3px solid {{ $color }};border-radius:6px;"><div style="font-size:19px;font-weight:800;color:#0f172a;">{{ number_format($value) }}</div><div style="margin-top:4px;color:#64748b;font-size:10px;font-weight:800;text-transform:uppercase;line-height:1.25;">{{ $label }}</div></div></td>
            @endforeach
        </tr></table></td></tr>
        <tr><td style="padding:0 30px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="width:50%;padding:0 8px 0 0;vertical-align:top;"><div style="border:1px solid #e2e8f0;border-radius:7px;overflow:hidden;"><div style="padding:10px 12px;background:#f8fafc;color:#334155;font-size:12px;font-weight:800;">Inspecciones por centro</div>@forelse(array_slice($centers,0,5,true) as $label => $count)<div style="padding:8px 12px;border-top:1px solid #e2e8f0;color:#475569;font-size:12px;">{{ $label }} <strong style="float:right;color:#21064f;">{{ $count }}</strong></div>@empty<div style="padding:10px 12px;color:#64748b;font-size:12px;">Sin centros informados.</div>@endforelse</div></td><td style="width:50%;padding:0 0 0 8px;vertical-align:top;"><div style="border:1px solid #e2e8f0;border-radius:7px;overflow:hidden;"><div style="padding:10px 12px;background:#f8fafc;color:#334155;font-size:12px;font-weight:800;">Frecuencia de medidas</div>@forelse(array_slice($frequencies,0,5,true) as $label => $count)<div style="padding:8px 12px;border-top:1px solid #e2e8f0;color:#475569;font-size:12px;">{{ $label }} <strong style="float:right;color:#b91c1c;">{{ $count }}</strong></div>@empty<div style="padding:10px 12px;color:#64748b;font-size:12px;">Sin medidas informadas.</div>@endforelse</div></td></tr></table></td></tr>
        <tr><td style="padding:0 30px 8px;"><div style="font-size:13px;font-weight:800;color:#334155;">Últimas inspecciones del período</div></td></tr>
        <tr><td style="padding:0 30px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:7px;overflow:hidden;"><tr><td style="padding:9px 10px;background:#f8fafc;color:#475569;font-size:10px;font-weight:800;text-transform:uppercase;">Fecha</td><td style="padding:9px 10px;background:#f8fafc;color:#475569;font-size:10px;font-weight:800;text-transform:uppercase;">Centro / área</td><td style="padding:9px 10px;background:#f8fafc;color:#475569;font-size:10px;font-weight:800;text-transform:uppercase;">Condiciones</td><td style="padding:9px 10px;background:#f8fafc;color:#475569;font-size:10px;font-weight:800;text-transform:uppercase;">Medidas</td></tr>@forelse($recent as $record)@php($frecuenciasRegistro = collect(explode('|', trim((string) $record->frecuencias_text, '|')))->filter()->unique()->implode(', '))<tr><td style="padding:10px;border-top:1px solid #e2e8f0;color:#475569;font-size:11px;vertical-align:top;white-space:nowrap;">{{ $record->fecha_inspeccion?->format('d/m/Y') ?? 'Sin fecha' }}<br>{{ $record->hora_inspeccion }}</td><td style="padding:10px;border-top:1px solid #e2e8f0;vertical-align:top;"><div style="color:#111827;font-size:12px;font-weight:800;">{{ $record->centro ?: 'Sin centro' }}</div><div style="margin-top:3px;color:#64748b;font-size:11px;">{{ $record->area_inspeccionada ?: 'Sin área' }}</div></td><td style="padding:10px;border-top:1px solid #e2e8f0;color:#ff6b35;font-size:12px;font-weight:800;vertical-align:top;">{{ $record->condiciones_count }}</td><td style="padding:10px;border-top:1px solid #e2e8f0;vertical-align:top;"><div style="color:#15803d;font-size:12px;font-weight:800;">{{ $record->medidas_count }}</div><div style="margin-top:3px;color:#64748b;font-size:10px;">{{ $frecuenciasRegistro }}</div></td></tr>@empty<tr><td colspan="4" style="padding:16px;text-align:center;color:#64748b;font-size:12px;">No hay inspecciones para estos filtros.</td></tr>@endforelse</table></td></tr>
        <tr><td style="padding:0 30px 24px;"><div style="padding:12px 14px;border-left:4px solid #ff6b35;background:#fff7f3;border-radius:5px;color:#475569;font-size:12px;line-height:1.55;"><strong style="color:#334155;">Seguimiento:</strong> {{ number_format($analytics['inmediatas'] ?? 0) }} medidas requieren acción inmediata. La verificación registrada en Kizeo permite identificar su plazo de revisión.</div></td></tr>
        <tr><td align="center" style="padding:0 30px 28px;"><a href="{{ $dashboardUrl }}" style="display:inline-block;padding:12px 18px;background:#21064f;border-radius:5px;color:#fff;font-size:12px;font-weight:800;text-decoration:none;">Abrir dashboard con estos filtros</a></td></tr>
        <tr><td style="padding:16px 30px;background:#21064f;text-align:center;color:rgba(255,255,255,.58);font-size:11px;">&copy; {{ date('Y') }} SAEP Platform · Reporte solicitado desde PDR Inspección Preventiva</td></tr>
    </table>
</td></tr></table>
</body>
</html>
